version: "3"

includes:
  flutter: .taskfiles/Flutter.yml
  firebase: .taskfiles/Firebase.yml
  lb: .taskfiles/LevelBuilder.yml
  fastlane: .taskfiles/Fastlane.yml
  hugo: .taskfiles/Hugo.yml
  levels: Taskfile.Levels.yml
  release: Taskfile.Release.yml

tasks:
  default:
    silent: true
    cmds:
      - task --list

  # -----------------------------------------------------------------------------
  # High-level Orchestration

  setup:
    desc: Set up the project for development (Flutter, Go, and CocoaPods)
    run: once
    cmds:
      - task: flutter:get
      - task: lb:get
      - task: hugo:get
      - task: firebase:configure
      - task: _setup:ios:pod-install
      - task: _setup:macos:pod-install

  _setup:ios:pod-install:
    internal: true
    platforms: [darwin]
    cmds:
      - task: flutter:ios:pod-install

  _setup:macos:pod-install:
    internal: true
    platforms: [darwin]
    cmds:
      - task: flutter:macos:pod-install

  validate:
    desc: Validate code quality across all modules (analysis, format, tests, and builds)
    cmds:
      - bunx nx run-many -t lint test build

  fix:
    desc: Fix code quality and linting issues across all modules
    cmds:
      - task: format:all
      - task: lint:fix:all

  clean:
    desc: Clean the Flutter build cache
    cmds:
      - task: flutter:clean

  # -----------------------------------------------------------------------------
  # Common Shortcuts (Backwards Compatibility)

  get:
    desc: Shortcut for flutter:get
    cmds:
      - task: flutter:get

  upgrade:
    desc: Shortcut for flutter:upgrade
    cmds:
      - task: flutter:upgrade
      - task: lb:upgrade

  build:all:
    desc: Build all project components (Flutter web, Level Builder, and Hugo site)
    cmds:
      - bunx nx run-many -t build

  test:all:
    desc: Run tests for all modules (Flutter and Level Builder)
    cmds:
      - bunx nx run-many -t test

  analyze:all:
    desc: Run static analysis for all modules (Flutter analyze and Level Builder lint)
    cmds:
      - bunx nx run-many -t lint

  format:all:
    desc: Format code across all modules
    cmds:
      - task: flutter:format
      - task: lb:format

  format:check:all:
    desc: Check if code is formatted across all modules
    cmds:
      - bunx nx run-many -t lint

  lint:fix:all:
    desc: Fix linting issues across all modules
    cmds:
      - bunx nx run-many -t lint --fix

  lint:all:
    desc: Run linting for all modules
    cmds:
      - task: flutter:lint
      - task: lb:lint

  dev:
    desc: Run the application in dev mode
    cmds:
      - task: flutter:dev

  run:
    desc: Run the application (shorthand for flutter:serve:web)
    cmds:
      - task: flutter:serve:web

  serve:
    desc: Serve the application (shorthand for flutter:serve:web)
    cmds:
      - task: flutter:serve:web

  deploy:
    desc: Deploy the application to Firebase Hosting
    deps:
      - task: flutter:build:web
    cmds:
      - task: firebase:hosting:deploy
