// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3Im0n5U3PiYu6OfC_ERr9YzhoGlVPik',
    appId: '1:697900014066:web:97c78a6c780f8f46c1f36b',
    messagingSenderId: '697900014066',
    projectId: 'parable-bloom',
    authDomain: 'parable-bloom.firebaseapp.com',
    storageBucket: 'parable-bloom.firebasestorage.app',
    measurementId: 'G-E32S50NTZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-4KlglFZpbEbbGKl1tEdaMlml_UpGDck',
    appId: '1:697900014066:android:3f2b49ceb7551ec5c1f36b',
    messagingSenderId: '697900014066',
    projectId: 'parable-bloom',
    storageBucket: 'parable-bloom.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7-Hxx2nMVBujBmtwGiJ-ociYyrs0y1I',
    appId: '1:697900014066:ios:602ba81c4ad6f100c1f36b',
    messagingSenderId: '697900014066',
    projectId: 'parable-bloom',
    storageBucket: 'parable-bloom.firebasestorage.app',
    iosBundleId: 'com.garciaericn.parablebloom',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7-Hxx2nMVBujBmtwGiJ-ociYyrs0y1I',
    appId: '1:697900014066:ios:602ba81c4ad6f100c1f36b',
    messagingSenderId: '697900014066',
    projectId: 'parable-bloom',
    storageBucket: 'parable-bloom.firebasestorage.app',
    iosBundleId: 'com.garciaericn.parablebloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8S6rx2GX1bms80Dpad48GOLRU5DTNe3U',
    appId: '1:1005379493386:web:5ce12bd5f2d2825b1789f3',
    messagingSenderId: '1005379493386',
    projectId: 'parableweave',
    authDomain: 'parableweave.firebaseapp.com',
    storageBucket: 'parableweave.firebasestorage.app',
    measurementId: 'G-EYGHBP8ZLZ',
  );
}
