// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8S6rx2GX1bms80Dpad48GOLRU5DTNe3U',
    appId: '1:1005379493386:web:8477bb3a66efd9f81789f3',
    messagingSenderId: '1005379493386',
    projectId: 'parableweave',
    authDomain: 'parableweave.firebaseapp.com',
    storageBucket: 'parableweave.firebasestorage.app',
    measurementId: 'G-9YV8X65ZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEfIXkNCUD7q_HJPSq6SahzQegBIS3fwc',
    appId: '1:1005379493386:android:cb48ba8767aa471f1789f3',
    messagingSenderId: '1005379493386',
    projectId: 'parableweave',
    storageBucket: 'parableweave.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM58jPRARKT7ZrznXTqXydbUw2Wpnusuw',
    appId: '1:1005379493386:ios:74f559f1cf97c8ef1789f3',
    messagingSenderId: '1005379493386',
    projectId: 'parableweave',
    storageBucket: 'parableweave.firebasestorage.app',
    iosBundleId: 'com.garciaericn.parablebloom',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM58jPRARKT7ZrznXTqXydbUw2Wpnusuw',
    appId: '1:1005379493386:ios:74f559f1cf97c8ef1789f3',
    messagingSenderId: '1005379493386',
    projectId: 'parableweave',
    storageBucket: 'parableweave.firebasestorage.app',
    iosBundleId: 'com.garciaericn.parablebloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8S6rx2GX1bms80Dpad48GOLRU5DTNe3U',
    appId: '1:1005379493386:web:5ce12bd5f2d2825b1789f3',
    messagingSenderId: '1005379493386',
    projectId: 'parableweave',
    authDomain: 'parableweave.firebaseapp.com',
    storageBucket: 'parableweave.firebasestorage.app',
    measurementId: 'G-EYGHBP8ZLZ',
  );
}
