#!/usr/bin/env dart
// ignore_for_file: avoid_print

/// Coverage gate for the Flutter app.
///
/// Parses `apps/parable-bloom/coverage/lcov.info` (generated by
/// `flutter test --coverage`) and fails when line coverage drops below
/// the threshold. Baseline measured 2026-09-04: 51.3% (204 tests).
///
/// Usage:
///   flutter test --coverage --exclude-tags=level-solver  # from apps/parable-bloom
///   dart run scripts/check_coverage.dart [threshold]     # from repo root
library;

import 'dart:io';

void main(List<String> arguments) {
  final threshold = arguments.isEmpty ? 50.0 : double.parse(arguments.first);

  // Resolve from the script location so this works regardless of CWD
  // (Task runs it with dir: apps/parable-bloom).
  final repoRoot = Platform.script.toFilePath().contains('scripts')
      ? File(Platform.script.toFilePath()).parent.parent
      : Directory.current;
  final lcov = File('${repoRoot.path}/apps/parable-bloom/coverage/lcov.info');
  if (!lcov.existsSync()) {
    print('❌ coverage/lcov.info not found.');
    print('   Run this first from apps/parable-bloom:');
    print('   flutter test --coverage --exclude-tags=level-solver');
    exit(1);
  }

  var found = 0;
  var hit = 0;
  for (final line in lcov.readAsLinesSync()) {
    if (line.startsWith('DA:')) {
      found++;
      if (int.parse(line.substring(3).split(',')[1]) > 0) hit++;
    }
  }

  final pct = found == 0 ? 0.0 : 100.0 * hit / found;
  print(
    '📊 Line coverage: $hit/$found = ${pct.toStringAsFixed(1)}% '
    '(threshold: ${threshold.toStringAsFixed(0)}%)',
  );
  if (pct < threshold) {
    print('❌ Coverage is below threshold.');
    exit(1);
  }
  print('✅ Coverage gate passed.');
}
