name: Release Level Builder

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/tags/level-builder-v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output_name: level-builder-linux-amd64
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            output_name: level-builder-windows-amd64.exe
          - os: ubuntu-latest
            goos: darwin
            goarch: amd64
            output_name: level-builder-darwin-amd64
          - os: ubuntu-latest
            goos: darwin
            goarch: arm64
            output_name: level-builder-darwin-arm64

    name: Build (${{ matrix.goos }}/${{ matrix.goarch }})

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'

      - name: Setup Task
        uses: arduino/setup-task@v2

      - name: Build
        working-directory: tools/level-builder
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ../../${{ matrix.output_name }} .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.output_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
